### model
model_name_or_path: sft_model_path

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.1
# pref_ftx: 0.1

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: 
template: llama3
cutoff_len: 2048
# max_samples: 1024
overwrite_cache: true
preprocessing_num_workers: 12

### output
output_dir: 
logging_steps: 1
save_steps: 20
save_only_model: true
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 5.0e-7
num_train_epochs: 1.0
lr_scheduler_type: linear
# lr_scheduler_type: constant_with_warmup
warmup_ratio: 0.1
bf16: true

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# evaluation_strategy: steps
# eval_steps: 500
